name: firebase-deploy

on:
  push:
    branches:
      - reactjs

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env: 
      working-directory: ./conferencing-react
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
        working-directory: ${{env.working-directory}}
      - name: Build page
        run: npm run build
        working-directory: ${{env.working-directory}}
      - name: Download Artifact
        uses: actions/download-artifact@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy 
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_REACT }}